### ISSUE TITLE
Implement Facebook sign in

### ISSUE THREAD

**Issue by hyochan** [dooboolab/whatssub#6]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2420%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/dooboolab/whatssub/issues/6)

Implement `facebook` sign in ($20) + ($5)

- [ ] Follow [the read](https://docs.expo.io/versions/latest/sdk/facebook/#__next).
- [ ] Implement feature in your own dev `env` (creating your own facebook dev account). Only erase `facebook` secret before `PR`ing.
- [ ] Write minimal test code (don't need to be perfect).
- [ ] Write `readme` on how to manage `facebook` secrets in `config.ts`.
- [ ] Write necessary variables in `config.sample.ts`.
- [ ] Login with `firebase` after receiving `token`.
- [ ] Write a blog (extra $5) in one of [medium dooboolab](https://medium.com/@dooboolab) or [medium react-native-seoul](https://medium.com/react-native-seoul) if you prefer Korean.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $20.00)

- [<img src='https://avatars0.githubusercontent.com/u/27461460?v=4' alt='hyochan' width=24 height=24> hyochan](https://issuehunt.io/u/hyochan) ($20.00)
### Submitted pull Requests
- [#20 Implement Facebook sign in](https://issuehunt.io/r/dooboolab/whatssub/pull/20)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/dooboolab/whatssub/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by steinkim** [comment]
저 이 태스크 맡아도 될까요? @hyochan

**Comment by hyochan** [comment]
assigned @jongtaekchoi

**Comment by hyochan** [comment]
Closed via #20
