### ISSUE TITLE
Implement Google sign in

### ISSUE THREAD

**Issue by hyochan** [dooboolab/whatssub#7]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2420%20Funded-%2300A156.svg" />](https://issuehunt.io/r/dooboolab/whatssub/issues/7)

Implement `Google` sign in. ($20) + ($5)

- [ ] Follow [the read](https://docs.expo.io/versions/latest/sdk/google-sign-in/#__next)
- [ ] Implement feature in your own dev `env` (creating your own google dev account). Only erase `google` secret before `PR`ing.
- [ ] Write minimal test code (don't need to be perfect).
- [ ] Write `readme` on how to manage `google` secrets in `config.ts`.
- [ ] Write necessary variables in `config.sample.ts`.
- [ ] Login with `firebase` after receiving `token`.
- [ ] Write a blog (extra $5) in one of [medium dooboolab](https://medium.com/@dooboolab) or [medium react-native-seoul](https://medium.com/react-native-seoul) if you prefer Korean.

** Note that our appId is `com.dooboolab.whatssub` **

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $20.00)

- [<img src='https://avatars0.githubusercontent.com/u/27461460?v=4' alt='hyochan' width=24 height=24> hyochan](https://issuehunt.io/u/hyochan) ($20.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/dooboolab/whatssub/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by kty1965** [comment]
이건 저도해보고 싶습니다!

**Comment by hyochan** [comment]
@kty1965 Assigned!

**Comment by hyochan** [comment]
@kty1965 
![image](https://user-images.githubusercontent.com/27461460/60360748-72a74180-9a17-11e9-9cdb-3afa993486ce.png)
Above is expected in `expo client`. You should test this is standalone app following the [guide](https://docs.expo.io/versions/latest/distribution/building-standalone-apps/) : sweat_smile:.
I think you've got bit `time-consuming` task. However, I think it would bring you great experience having to work with `expo` standalone app 🙏 .

![image](https://user-images.githubusercontent.com/27461460/60360734-69b67000-9a17-11e9-896c-04d6b7abf9ce.png)
